#!/bin/bash -e
# Launch the web interface

#Thanks to http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/../bin/activate
cd $DIR && ./pcb_drill_web.py "${@}"
deactivate
